<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\GQ.Common\GQ.Common.csproj" />
      <ProjectReference Include="..\GQ.Database\GQ.Database.csproj" />
      <ProjectReference Include="..\GQ.Entities\GQ.Entities.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AutoMapper" Version="15.1.0" />
    </ItemGroup>

</Project>
